### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by shadiabuhilal** [yahoo/babel-plugin-react-intl#146]
Any idea on when Babel 7 will be support for this repo?

**Comment by redonkulus** [comment]
There is an ongoing PR being worked on now https://github.com/yahoo/babel-plugin-react-intl/pull/145

**Comment by w01fgang** [comment]
@okuryu can't make it work with `transform`.
```
const { transform } = require('@babel/core');
...
const result = await transform(code, { presets, plugins });
```
I receive the error
```
error TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1456:5)
    at Object.extname (/my_project/node_modules/upath/build/code/upath.js:55:33)
    at PluginPass.post (/my_project/node_modules/babel-plugin-react-intl/lib/index.js:204:45)
    at transformFile (/my_project/node_modules/@babel/core/lib/transformation/index.js:94:27)
    at runSync (/my_project/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at transformSync (/my_project/node_modules/@babel/core/lib/transform.js:43:38)
    at transform (/my_project/node_modules/@babel/core/lib/transform.js:22:38)
```
