### ISSUE TITLE
Error: Cannot find module 'upath'

### ISSUE THREAD

**Issue by MartinCerny-awin** [yahoo/babel-plugin-react-intl#151]
I am using babel-plugin-react-intl in react-native project. When I try to extract messages I get an error:
```
$ babel --plugins react-intl src/*
Error: Cannot find module 'upath'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Volumes/sites/monyl/node_modules/babel-plugin-react-intl/lib/index.js:22:33)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

My .babelrc looks like this:
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    [
      "react-intl",
      {
        "messagesDir": "./i18n/messages",
        "enforceDescriptions": false
      }
    ]
  ]
}
```

**Comment by serwer-WittGruppe** [comment]
Same here!

**Comment by serwer-WittGruppe** [comment]
See also: https://github.com/yahoo/babel-plugin-react-intl/pull/145/files#r218506404

**Comment by bj00rn** [comment]
#154

**Comment by redonkulus** [comment]
Closed via https://github.com/yahoo/babel-plugin-react-intl/pull/154
