### ISSUE TITLE
Error: Plugin 5 specified in ... an invalid property of "messagesDir"

### ISSUE THREAD

**Issue by forabi** [yahoo/babel-plugin-react-intl#30]
```
Error: Plugin 5 specified in "/home/f/dm/.babelrc" provided an invalid property of "messagesDir"
    at Plugin.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:127:13)
    at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:169:12)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:199:30
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:175:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:273:36)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:223:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:366:16)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:410:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
```

.babelrc

```json
{
  "presets": ["es2015-node5", "stage-3", "react"],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-decorators",
    "transform-runtime",
    "react-intl", {
      "messagesDir": "./build/messages"
    }
  ],
  "sourceMaps": "both"
}
```

```
> npm ls | grep intl
├─┬ babel-plugin-react-intl@2.0.0
│ ├── intl-messageformat-parser@1.2.0
├─┬ react-intl@2.0.0-beta-2
│ ├── intl-format-cache@2.0.5
│ ├── intl-messageformat@1.2.0
│ └── intl-relativeformat@1.2.0

> node -v
v5.4.0
```

**Comment by GertjanReynaert** [comment]
@forabi You should wrap the `react-intl` plugin in an array, like this
```
{
  "presets": ["es2015-node5", "stage-3", "react"],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-decorators",
    "transform-runtime",
    [
      "react-intl", {
        "messagesDir": "./build/messages"
      }
    ]
  ],
  "sourceMaps": "both"
}
```
I'm not sure if you should also do this with the plugins without extra config, so that might be something you wan't to consider if the above doesn't work straight away.

**Comment by forabi** [comment]
Oops! That fixed it. Thanks!
