### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by jvorcak** [yahoo/babel-plugin-react-intl#36]
Hi,

I've tried to install react-intl@next for my react starter project and after I've installed npm3 on my system, I've started to experience the following error which goes away if I remove `babel-plugin-react-intl` from my project.

```
Jans-MacBook-Pro-2:learning2016 janvorcak$ npm3 start

> redux-universal-example@0.0.0 start /Users/janvorcak/learning2016
> node src/server/index.js

/Users/janvorcak/learning2016/node_modules/babel-core/lib/transformation/file/index.js:548
      throw err;
      ^

TypeError: /Users/janvorcak/learning2016/src/client/counter/Counter.js: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at PluginPass.exit (/Users/janvorcak/learning2016/node_modules/babel-plugin-react-intl/lib/index.js:155:46)
    at newFn (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/path/context.js:116:8)
    at TraversalContext.visitQueue (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/janvorcak/learning2016/node_modules/babel-traverse/lib/context.js:197:19)
```

When I remove a plugin from my setup, everything works fine. Could it be a bug?
You can reproduce it by

```
git clone https://github.com/jvorcak/universal-react-kit.git
# upgrade babel-plugin-react-intl to latest version
cd universal-react-kit
npm3 install
npm3 start
```

Thanks for the work you're doing with this plugin.

**Comment by orhanhenrik** [comment]
I am experiencing exactly the same issue. This worked with babel5 (1.x version of module), but when updating to babel6 I am getting the same error messages as you (2.x version of module).

**Comment by evenchange4** [comment]
I create a PR to fix this problem #37 .

Downgrade to `2.0.0`  may be a workaround.

**Comment by jvorcak** [comment]
@evenchange4 thanks, downgrading is a workaround. Your patch seems to solve the issue. Good job!

**Comment by michaelahlers** [comment]
:+1:

Reverting to 2.0.0 worked for me, too.

**Comment by ericf** [comment]
This is now fixed in 2.1.1, sorry!

**Comment by iam-peekay** [comment]
@ericf I get this same issue regardless of whether I use 2.0.0 or 2.1.1

**Comment by ericf** [comment]
@iam-peekay can you try the `@latest` which is current 2.1.3?

**Comment by iam-peekay** [comment]
@ericf sorry for not responding sooner! It happened to be because I was on Node v6.2 ...the error was gone once I installed Node v5.11.1

thank you.
