### ISSUE TITLE
Module build failed because provided an invalid property

### ISSUE THREAD

**Issue by Andersos** [yahoo/babel-plugin-react-intl#83]
I'm getting an error from Webpack when trying to use this plugin. It looks to be the same as this issue https://github.com/yahoo/babel-plugin-react-intl/issues/40.
```bash
ERROR in ./src/index.jsx
Module build failed: Error: Plugin 1 specified in "base" provided an invalid property of "messagesDir"
    at Plugin.init (/Users/u/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:148:12)
    at /Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:36)
    at OptionManager.init (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at File.initOptions (/Users/u/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/u/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/u/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
 @ multi main
```

    module: {
        loaders: [cssLoader,
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015'],
                    plugins: ['react-intl', {
                        "messagesDir": "./build/lang/",
                        "enforceDescriptions": true,
                    }],
                },
            },
        ],
    },

```js
    "webpack": "^1.13.2"
    "babel-plugin-react-intl": "^2.2.0",
    "eslint": "^3.8.1",
```

**Comment by ericf** [comment]
Could you create a simple reproducible example that shows the issue?

**Comment by Andersos** [comment]
I tried to create a simple example. 4 files in one folder and then running `npm start` returns the error:

```bash
ERROR in ./index.jsx
Module build failed: TypeError: Plugin 0 specified in "base" was expected to return a function but returned "undefined"
    at Function.normalisePlugin (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:144:15)
    at /Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/u/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/u/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/u/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/u/node_modules/babel-loader/index.js:38:20)
 @ multi main

```


package.json
```json
{
  "name": "demo",
  "version": "0.0.1",
  "description": "",
  "scripts": {
    "start": "webpack-dev-server --config ./webpack.config.js --inline --hot --content-base . --history-api-fallback"
  },
  "dependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-intl": "^2.1.5",
    "webpack": "^1.13.3",
    "webpack-dev-server": "^1.16.2"
  }
}
```
webpack.config.js
```js
module.exports = {
    entry: './index.jsx',

    output: {
        filename: 'bundle.js',
        publicPath: '/',
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015'],
                    plugins: ['react-intl', {
                        "messagesDir": "/build/lang/",
                        "enforceDescriptions": true,
                    }],
                },
            },
        ],
    },
};

```
index.jsx
```jsx
import { render } from 'react-dom';
import React from 'react';
import { IntlProvider, FormattedMessage } from 'react-intl';

render(
    <IntlProvider locale={navigator.language}>
        <FormattedMessage
                        id='yo'
                        description='Greeting to welcome'
                        defaultMessage='Yo hello'
                    />
    </IntlProvider>,
    document.getElementById('app')
);
```
index.html
```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Yo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="app"></div>
    <script src="/bundle.js"></script>
</body>
</html>
```

**Comment by Andersos** [comment]
I tried to create a simple example. 4 files in one folder and then running `npm start` returns the error:

```bash
ERROR in ./index.jsx
Module build failed: TypeError: Plugin 0 specified in "base" was expected to return a function but returned "undefined"
    at Function.normalisePlugin (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:144:15)
    at /Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/u/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/u/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/u/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/u/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/u/node_modules/babel-loader/index.js:38:20)
 @ multi main

```


package.json
```json
{
  "name": "demo",
  "version": "0.0.1",
  "description": "",
  "scripts": {
    "start": "webpack-dev-server --config ./webpack.config.js --inline --hot --content-base . --history-api-fallback"
  },
  "dependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-intl": "^2.1.5",
    "webpack": "^1.13.3",
    "webpack-dev-server": "^1.16.2"
  }
}
```
webpack.config.js
```js
module.exports = {
    entry: './index.jsx',

    output: {
        filename: 'bundle.js',
        publicPath: '/',
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015'],
                    plugins: ['react-intl', {
                        "messagesDir": "/build/lang/",
                        "enforceDescriptions": true,
                    }],
                },
            },
        ],
    },
};

```
index.jsx
```jsx
import { render } from 'react-dom';
import React from 'react';
import { IntlProvider, FormattedMessage } from 'react-intl';

render(
    <IntlProvider locale={navigator.language}>
        <FormattedMessage
                        id='yo'
                        description='Greeting to welcome'
                        defaultMessage='Yo hello'
                    />
    </IntlProvider>,
    document.getElementById('app')
);
```
index.html
```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Yo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="app"></div>
    <script src="/bundle.js"></script>
</body>
</html>
```

**Comment by Andersos** [comment]
I also tried creating a `.babelrc` file using the same files above but adding

.babelrc
```json
{
    "presets": ["react", "es2015"],
    "plugins": [
        ["react-intl",
            {
                "messagesDir": "./build/messages/"
            }
        ]
    ]
}
```

Changing webpack.config.js to 
```js
module.exports = {
    entry: './index.jsx',

    output: {
        filename: 'bundle.js',
        publicPath: '/',
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
            },
        ],
    },
};
```

But I seem to get the same error:

ERROR in ./index.jsx
Module build failed: TypeError: Plugin 0 specified in "/Users/u/.babelrc" was expected to return a function but returned "undefined"

**Comment by ericf** [comment]
You need to actually install this package:
```
npm i --save-dev babel-plugin-react-intl
```

**Comment by Andersos** [comment]
I'm sorry I forgot that in the example but it still produces the same error message even if this module is added as a dependency.

**Comment by ericf** [comment]
I'm not sure. Have you stepped through the build process? Does it work if you just run `babel index.jsx`? Can you create a repo so I can reproduce the error?

**Comment by Andersos** [comment]
It works when running `babel index.jsx`.
I have not stepped through the build process. I'm not quite sure how I would do that but I will try and read up on it. 

I created a repo here https://github.com/Andersos/demo

**Comment by ericf** [comment]
Having both a `.babelrc` and babel config in the `webpack.config.js` will cause the babel to merge these configs and therefore run every transform multiple times. You should pick one or the other. Applying this diff to your `webpack.config.js` got the build to work for me locally:
```diff
diff --git a/webpack.config.js b/webpack.config.js
index 6c8d514..2b2153b 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -10,13 +10,7 @@ module.exports = {
             {
                 test: /\.(js|jsx)$/,
                 exclude: /node_modules/,
-                loader: 'babel-loader',
-                query: {
-                    presets: ['react', 'es2015'],
-                    plugins: ['react-intl', {
-                        "messagesDir": "./build/lang/"
-                    }],
-                },
+                loader: 'babel-loader'
             },
         ],
     },
```

**Comment by Andersos** [comment]
Im also getting it to work with only using the `.babelrc` file. Is it possible to get it to work when specifying the query params in the Webpack config? Anyway, it will work specifying the config in the babel file so I will close this issue. Thanks for the help.

**Comment by ericf** [comment]
I don't understand Webpack loaders and babel-loader well enough to say.

**Comment by Andersos** [comment]
Anyway, thanks for the help 🌮
